baseURL = "https://gimo.me/"
languageCode = "en-us"
title = "熊ノ介のブログ"
theme = "minimal"
disqusShortname = "gimome" # delete this to disable disqus comments
googleAnalytics = "UA-50840195-1"
hasCJKLanguage = true

[params]
    author = "熊ノ介"
    description = "面白いことをたくさんしたい"
    githubUsername = "masakichi"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Noto Serif" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python",]

[[menu.main]]
    url = "/"
    name = "ホーム"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "日記"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "プロジェクト"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:self@gimo.me"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/masakichi/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/gimo_me/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://t.me/yuanji"
    name = "telegram"
    weight = 4

[[menu.icon]]
    url = "https://instagram.com/gimo_me/"
    name = "instagram"
    weight = 5
