baseURL = "https://blog.gimo.me/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "Yuanji's Blog"
theme = "futu"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10                                              # 首页每页显示的文章数
disqusShortname = "gimome"      # disqus_shortname
googleAnalytics = "G-YL6RBN684E"

[author]
  name = "Yuanji"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"
#[[menu.main]]
#  name = "Categories"
#  weight = 40
#  identifier = "categories"
#  url = "/categories/"

[params]
  since = "2016"            # Site creation time          # 站点建立时间

  keywords = ["Yuanji", "元吉", "日语", "编程"]
  description = "Yuanji's Blog, 元吉的博客"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archivePaginate = 100

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  # TODO
  toc = true                                                                            # 是否开启目录

  googleVerification = "MgUc_ybvVWaRA5z2rsL4hzS5DwH9xdvKQFNthWOoLEg"  # Google Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ["custom.css"]
  customJS = []

  gitRepo = "https://github.com/masakichi/nikki"

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    # TODO
    enable = false

  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = true
    hint = 180               # Display hint if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示提醒
    warn = 360              # Display warning if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示警告


  [params.social]
    a-email = "mailto:self@gimo.me"
    b-telegram = "https://t.me/yuanji"
    c-douban = "https://douban.com/people/masakichi"
    d-twitter = "https://twitter.com/gimo_me"
    e-github = "https://github.com/masakichi"
    f-instagram = "https://instagram.com/gimo_me"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# Uncomment these options to make hugo output .md files.
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS", "MarkDown"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
