baseURL = "https://blog.yuanji.dev"
defaultContentLanguage = "zh-cn"       # https://github.com/gohugoio/hugo/issues/7344
defaultContentLanguageInSubdir = false
buildDrafts = true
buildFuture = true
title = "Yuanji's Blog"
theme = "futu"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true            # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10                    # 首页每页显示的文章数
timeout = "300s"
# googleAnalytics = "G-YL6RBN684E"

[services]
  [services.disqus]
    shortname = 'gimome'

[permalinks]
  remarks = '/:section/:year-:month-:day/'

[imaging]
  quality = 75

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']

[params]
  keywords = ["Yuanji", "元吉", "日语", "日本", "VPS", "Linux"]
  description = "Yuanji's Blog, 元吉的博客"
  ampLogo = "logo-600x60.png"
  # Site creation time
  since = "2016"
  homePaginate = 10
  paginate = 10
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006/01/02"
  # Whether display TOC or not.
  toc = true
  enableRelated = true
  enableShare = true
  googleVerification = "MgUc_ybvVWaRA5z2rsL4hzS5DwH9xdvKQFNthWOoLEg"
  # cfBeaconToken = "744413db6a4649cd861280314303b5a9"
  enableZoomJS = true
  telegramChannel = "yuanji_chan"

[params.social]
  twitter = "yuanji_dev"

[params.author]
  name = "Yuanji"
  url = "https://blog.yuanji.dev"

[params.git]
  repo = "https://github.com/yuanji-dev/nikki"
  branch = "main"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.googleAnalytics]
  anonymizeIP = true # 12.214.31.144 -> 12.214.31.0
[privacy.youtube]
  privacyEnhanced = true

# Uncomment these options to make hugo output .md files.
[mediaTypes]
[mediaTypes."text/markdown"]
  suffixes = ["md"]

[outputFormats.Markdown]
  mediaType = "text/markdown"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "Markdown"]
  page = ["HTML", "AMP", "Markdown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[markup]
[markup.tableOfContents]
  startLevel = 2
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
[markup.highlight]
  anchorLineNos = true
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  noClasses = false
  noHl = false
  style = 'rose-pine-dawn'
  tabWidth = 4


[languages]
[languages.zh-CN]
  title = "Yuanji's Blog"
  languageCode = 'zh-CN'
  languageName = '简体中文'
[languages.zh-CN.params]
  description = "Yuanji's Blog。分享技术、日语，记录学习、生活。"
  # https://github.com/gohugoio/hugo/blob/2fc2e9c8718db2fe60f03bcf3661f449851cfe5f/tpl/tplimpl/embedded/templates/twitter_cards.html
  images = ["cover.png"]
  mainSections = ["posts"]
# https://gohugo.io/content-management/menus/
[languages.zh-CN.menu]
[[languages.zh-CN.menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.zh-CN.menu.main]]
  name = "文章"
  weight = 20
  identifier = "posts"
  url = "/posts/"
[[languages.zh-CN.menu.main]]
  name = "月历"
  weight = 30
  identifier = "calendar"
  url = "/calendar/"
[[languages.zh-CN.menu.main]]
  name = "标签"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[languages.zh-CN.menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"
[[languages.zh-CN.menu.main]]
  name = "订阅"
  weight = 60
  identifier = "rss"
  url = "/index.xml"

[languages.en]
  title = "Yuanji's Blog"
  languageCode = 'en'
  languageName = 'English'
[languages.en.params]
  images = ["cover.en.png"]
[[languages.en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.en.menu.main]]
  name = "Posts"
  weight = 20
  identifier = "posts"
  url = "/posts/"
[[languages.en.menu.main]]
  name = "Calendar"
  weight = 30
  identifier = "calendar"
  url = "/calendar/"
[[languages.en.menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
[[languages.en.menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"
[[languages.en.menu.main]]
  name = "RSS"
  weight = 60
  identifier = "rss"
  url = "/index.xml"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    type = 'basic'
    weight = 100
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    type = 'basic'
    weight = 10
[[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    type = 'basic'
    weight = 80
