baseURL = "https://gimo.me/"
languageCode = "zh-cmn-Hans"
title = "熊之介的日记"
theme = "minimal"
disqusShortname = "gimome" # delete this to disable disqus comments
googleAnalytics = "UA-50840195-1"
hasCJKLanguage = true
enableGitInfo = true

[blackfriday]
    hrefTargetBlank = true

[params]
    author = "熊之介"
    description = ""
    githubUsername = "masakichi"
    showBorder = true
    backgroundColor = "#F6F6F6"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python",]
    ghrepo = "https://github.com/masakichi/nikki"
    dateFormat = "2006/01/02"

[[menu.main]]
    url = "/"
    name = "主页"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "日记"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "项目"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:self@gimo.me"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/masakichi"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/gimo_me"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://t.me/yuanji"
    name = "telegram"
    weight = 4

[[menu.icon]]
    url = "https://instagram.com/gimo_me"
    name = "instagram"
    weight = 5

[related]
    threshold = 80

[[related.indices]]
    name  = "tags"
    weight = 100

[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
