# TODO:
# 1. add a cover for home page.
# 2. review meta info of archives, about page.
# 3. review head meta template

baseURL = "https://blog.gimo.me/"
defaultContentLanguage = "zh-cn"       # https://github.com/gohugoio/hugo/issues/7344
defaultContentLanguageInSubdir = false
title = "Yuanji's Blog"
theme = "futu"
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true            # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 10                    # 首页每页显示的文章数
disqusShortname = "gimome"       # disqus_shortname
# googleAnalytics = "G-YL6RBN684E"

[author]
  name = "Yuanji"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
  lastmod = ['lastmod', ':git', 'date', 'publishDate']

[params]
  keywords = ["Yuanji", "元吉", "日语", "编程"]
  description = "Yuanji's Blog, 元吉的博客"
  # Site creation time
  since = "2016"
  paginate = 10
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006/01/02"
  # Whether display TOC or not.
  toc = true
  googleVerification = "MgUc_ybvVWaRA5z2rsL4hzS5DwH9xdvKQFNthWOoLEg"

[params.git]
  repo = "https://github.com/masakichi/nikki"
  branch = "main"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.googleAnalytics]
  anonymizeIP = true # 12.214.31.144 -> 12.214.31.0
[privacy.youtube]
  privacyEnhanced = true

# Uncomment these options to make hugo output .md files.
[mediaTypes]
[mediaTypes."text/plain"]
  suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS", "MarkDown"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[markup]
[markup.tableOfContents]
  startLevel = 2
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  anchorLineNos = true
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  noHl = false
  style = 'monokai'
  tabWidth = 4

# weird, not mentioned on https://gohugo.io/variables/site/
[social]
  twitter = "gimo_me"

[languages]
[languages.zh-CN]
  title = "Yuanji's Blog"
  languageCode = 'zh-CN'
  languageName = '简体中文'
# https://gohugo.io/content-management/menus/
[languages.zh-CN.menu]
[[languages.zh-CN.menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.zh-CN.menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/archives/"
[[languages.zh-CN.menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[languages.zh-CN.menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[languages.en]
  title = "Yuanji's Blog"
  languageCode = 'en'
  languageName = 'English'
[[languages.en.menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[languages.en.menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/archives/"
[[languages.en.menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[languages.en.menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"
